version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:stretch
    steps:
      - checkout
      - run:
          name: Prepare
          command: |
            apt-get update -y
            apt-get install -y shellcheck
      - run:
          name: shellcheck
          command: |
            echo "running shellcheck..."
            shellcheck *.sh
